### ISSUE TITLE
Error: Variable $version of type String! was provided invalid value

### ISSUE THREAD

**Issue by chinalwb** [JackHowa/delete-github-package-versions#7]
Hi, I was trying use this action to delete a version, my code looks like below:

```
    steps:
      - name: Delete package
        uses: jackhowa/delete-github-package-versions@v0.4.9
        with:
          version: '2.0.3' # The regex needs to be escaped!
          names: |
            com.chinalwb.libraries.droidlib
```

While running the script, the workflow failed with:

```
Run jackhowa/delete-github-package-versions@v0.4.9
  with:
    version: 2.0.3
    names: com.chinalwb.libraries.droidlib
  
    token: ***
    dry-run: false
    version-query-order: last
Fetching packages
Error: Variable $version of type String! was provided invalid value
```

I'm wondering what is the expect syntax to use this action, thanks!
